version: 1.0.{build}
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: 7hZHP5bLxlE8doYiQg6b79oF7wM6jlecs
before_build:
  - nuget restore ".\MonoAGS.sln"
build:
  project: .\MonoAGS.sln
  verbosity: minimal
test_script:
- ps: >-
    .\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:nunit-console.exe -register:user "-targetargs:""Tests\bin\$env:CONFIGURATION\Tests.dll"" /noshadow" -filter:"+[Engine*]*" -output:opencoverCoverage.xml
    
    .\packages\coveralls.net.0.6.0\tools\csmacnz.Coveralls.exe --opencover -i ./opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --jobId $env:APPVEYOR_JOB_ID
