version: 1.0.{build}
skip_tags: true
configuration: 
 - Debug
 - Release 
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - nuget restore ".\MonoAGS.sln"
build:
  project: .\MonoAGS.sln
  verbosity: minimal
test_script:
- ps: >-
    if($env:CONFIGURATION -eq "Debug")
    {
    .\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:.\packages\NUnit.Runners.2.6.4\tools\nunit-console.exe "-targetargs:""Tests\bin\Debug\Tests.dll"" /noshadow" -filter:"+[Engine*]*" -output:opencoverCoverage.xml
    
    .\packages\coveralls.net.0.6.0\tools\csmacnz.Coveralls.exe --opencover -i ./opencoverCoverage.xml --repoToken 7hZHP5bLxlE8doYiQg6b79oF7wM6jlecs
	}
